import type { Pitch } from './api/pitches';

export const mockPitches: Pitch[] = [
  {
    id: '1',
    name: 'Champions League Arena',
    description: 'State-of-the-art facility with professional-grade artificial turf. Perfect for competitive matches and training sessions. Features include floodlights, modern changing rooms, and spectator seating.',
    address: '123 Victory Lane',
    city: 'London',
    country: 'United Kingdom',
    latitude: 51.5074,
    longitude: -0.1278,
    pricePerHour: 85,
    surface: 'artificial',
    size: '11-a-side',
    facilities: ['Parking', 'Showers', 'Changing Rooms', 'Floodlights', 'WiFi', 'Cafe'],
    images: ['https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800'],
    rating: 4.9,
    totalReviews: 247,
    isAvailable: true,
    ownerId: 'owner1',
    ownerName: 'Elite Sports Management',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-11-01T14:30:00Z',
  },
  {
    id: '2',
    name: 'Green Valley Sports Complex',
    description: 'Beautiful natural grass pitch surrounded by scenic hills. Ideal for weekend games and tournaments. Well-maintained grounds with excellent drainage system.',
    address: '456 Meadow Road',
    city: 'Manchester',
    country: 'United Kingdom',
    latitude: 53.4808,
    longitude: -2.2426,
    pricePerHour: 70,
    surface: 'grass',
    size: '7-a-side',
    facilities: ['Parking', 'Changing Rooms', 'Equipment Rental', 'First Aid'],
    images: ['https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800'],
    rating: 4.7,
    totalReviews: 183,
    isAvailable: true,
    ownerId: 'owner2',
    ownerName: 'Valley Sports Ltd',
    createdAt: '2024-02-20T09:00:00Z',
    updatedAt: '2024-10-28T16:45:00Z',
  },
  {
    id: '3',
    name: 'Urban Futsal Center',
    description: 'Indoor futsal facility with climate control. Perfect for all-weather play. High-quality wooden floor and professional goals. Great for technical training.',
    address: '789 City Square',
    city: 'Birmingham',
    country: 'United Kingdom',
    latitude: 52.4862,
    longitude: -1.8904,
    pricePerHour: 60,
    surface: 'indoor',
    size: '5-a-side',
    facilities: ['Indoor', 'Air Conditioning', 'Showers', 'Lockers', 'Vending Machines'],
    images: ['https://images.unsplash.com/photo-1551958219-acbc608c6377?w=800'],
    rating: 4.8,
    totalReviews: 312,
    isAvailable: true,
    ownerId: 'owner3',
    ownerName: 'Futsal Pro UK',
    createdAt: '2024-03-10T11:00:00Z',
    updatedAt: '2024-11-05T10:20:00Z',
  },
  {
    id: '4',
    name: 'Riverside Athletic Ground',
    description: 'Hybrid pitch combining natural and artificial grass for optimal playing conditions year-round. Located by the river with stunning views.',
    address: '321 Waterfront Drive',
    city: 'Liverpool',
    country: 'United Kingdom',
    latitude: 53.4084,
    longitude: -2.9916,
    pricePerHour: 75,
    surface: 'hybrid',
    size: '11-a-side',
    facilities: ['Parking', 'Showers', 'Changing Rooms', 'Physiotherapy Room', 'Bar'],
    images: ['https://images.unsplash.com/photo-1624880357913-a8539238245b?w=800'],
    rating: 4.6,
    totalReviews: 156,
    isAvailable: false,
    ownerId: 'owner4',
    ownerName: 'Riverside Sports Club',
    createdAt: '2024-04-05T08:30:00Z',
    updatedAt: '2024-11-03T13:15:00Z',
  },
  {
    id: '5',
    name: 'Skyline 5-a-Side Arena',
    description: 'Rooftop pitch with panoramic city views. Latest generation 3G artificial turf. Perfect for evening games under the stars.',
    address: '555 Tower Heights',
    city: 'London',
    country: 'United Kingdom',
    latitude: 51.5155,
    longitude: -0.0922,
    pricePerHour: 55,
    surface: 'artificial',
    size: '5-a-side',
    facilities: ['Rooftop', 'Floodlights', 'Changing Rooms', 'City Views', 'Refreshments'],
    images: ['https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800'],
    rating: 4.9,
    totalReviews: 428,
    isAvailable: true,
    ownerId: 'owner5',
    ownerName: 'Sky Sports Venues',
    createdAt: '2024-01-25T12:00:00Z',
    updatedAt: '2024-11-06T09:30:00Z',
  },
  {
    id: '6',
    name: 'Heritage Park Stadium',
    description: 'Traditional grass pitch in a historic park setting. Perfect for weekend leagues and family-friendly matches. Beautiful mature trees surrounding the pitch.',
    address: '88 Heritage Way',
    city: 'Edinburgh',
    country: 'United Kingdom',
    latitude: 55.9533,
    longitude: -3.1883,
    pricePerHour: 65,
    surface: 'grass',
    size: '7-a-side',
    facilities: ['Parking', 'Changing Rooms', 'Benches', 'Picnic Area'],
    images: ['https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800'],
    rating: 4.5,
    totalReviews: 94,
    isAvailable: true,
    ownerId: 'owner6',
    ownerName: 'Edinburgh Parks Department',
    createdAt: '2024-05-12T07:00:00Z',
    updatedAt: '2024-10-30T15:00:00Z',
  },
  {
    id: '7',
    name: 'Pro Training Ground',
    description: 'Professional-grade facility used by local academy teams. Multiple pitches available, including training areas and full-size match pitch.',
    address: '200 Academy Road',
    city: 'Manchester',
    country: 'United Kingdom',
    latitude: 53.4631,
    longitude: -2.2913,
    pricePerHour: 95,
    surface: 'hybrid',
    size: '11-a-side',
    facilities: ['Parking', 'Showers', 'Changing Rooms', 'Gym', 'Medical Room', 'Analysis Suite', 'Cafe'],
    images: ['https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800'],
    rating: 4.8,
    totalReviews: 201,
    isAvailable: true,
    ownerId: 'owner7',
    ownerName: 'Pro Soccer Academy',
    createdAt: '2024-02-28T10:30:00Z',
    updatedAt: '2024-11-04T11:45:00Z',
  },
  {
    id: '8',
    name: 'Downtown Quick Pitch',
    description: 'Convenient city center location for lunch-time and after-work games. Compact but well-equipped 5-a-side facility.',
    address: '12 Business District',
    city: 'London',
    country: 'United Kingdom',
    latitude: 51.5142,
    longitude: -0.0931,
    pricePerHour: 50,
    surface: 'artificial',
    size: '5-a-side',
    facilities: ['Showers', 'Lockers', 'WiFi', 'Snack Bar'],
    images: ['https://images.unsplash.com/photo-1486286701208-1d58e9338013?w=800'],
    rating: 4.4,
    totalReviews: 167,
    isAvailable: true,
    ownerId: 'owner8',
    ownerName: 'City Sports Network',
    createdAt: '2024-06-01T09:00:00Z',
    updatedAt: '2024-11-02T14:00:00Z',
  },
  {
    id: '9',
    name: 'Seaside Sports Arena',
    description: 'Beach-adjacent pitch with ocean views. Fresh sea breeze and excellent natural drainage. Popular for summer tournaments.',
    address: '45 Coastal Road',
    city: 'Brighton',
    country: 'United Kingdom',
    latitude: 50.8225,
    longitude: -0.1372,
    pricePerHour: 68,
    surface: 'artificial',
    size: '7-a-side',
    facilities: ['Parking', 'Showers', 'Beach Access', 'BBQ Area', 'Changing Rooms'],
    images: ['https://images.unsplash.com/photo-1556056504-5c7696c4c28d?w=800'],
    rating: 4.7,
    totalReviews: 223,
    isAvailable: true,
    ownerId: 'owner9',
    ownerName: 'Coastal Recreation Ltd',
    createdAt: '2024-03-15T08:00:00Z',
    updatedAt: '2024-10-29T16:30:00Z',
  },
];
